# Spring Configuration
spring:
  application:
    name: @project.name@
  main:
    allow-bean-definition-overriding: true
  h2:
    console:
      enabled: true
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:h2:mem:testdb

# Swagger Documentation
swagger:
  service:
    version: "1.0.0"
    title: ${spring.application.name}
    description: "Skeleton app swagger"
